name: Node
on: [push]

jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@master
        with:
          node-version: '18.x'

      - name: Install
        run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Depcheck
        run: yarn depcheck || true

      - name: Prettier
        run: yarn prettier || true

      - name: Tests
        run: yarn test || true

      - name: Build
        run: yarn build

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=config/sonar-project.properties
